const ACTIONS = {
  ADD_PROVIDER: "ADD_PROVIDER",
  EDIT_PROVIDER: "EDIT_PROVIDER",
  DELETE_PROVIDER: "DELETE_PROVIDER",
  SAVE_VIDEOS: "SAVE_VIDEOS",
  LIKE_VIDEO: "LIKE_VIDEO",
  TOGGLE_CLICKED: "TOGGLE_CLICKED"
};

export { ACTIONS };
